coverage:
    needs: [ check ]
 
    name: coverage
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
    - run: |
          pip install poetry
          make install
    - uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: cb70907c5930cf20da6e0378115e0e3a01d5e7e1017b746855cede87d4ee3924
      with:
        coverageCommand: make test-coverage
